### ISSUE TITLE
[Ivy] rewrite directives in Ivy after stable release

### ISSUE THREAD

**Issue by xmlking** [angular/flex-layout#1002]
# Design Discussion

As mentioned in https://github.com/angular/flex-layout/issues/1002#issuecomment-455967676, when Ivy is stable, we can use this issue to track rewriting the library with Ivy-specific features.

<details><summary>Original Report</summary>
# Bug Report

Unable to enable  `Ivy` to project.

#### What is the expected behavior?

should be able to enable `Ivy` 

#### What is the current behavior?

Error 

#### What are the steps to reproduce?
 
create new project with `--experimental-ivy` 
```
ng new ngx-starter-kit  --prefix=ngx  --experimental-ivy
ng add @angular/material
npm i @angular/flex-layout
ng serve 
```

Error when dev server started
```
Compiling @angular/flex-layout/extended - fesm2015
Error: Failed to resolve @Directive.inputs
    at parseFieldArrayValue (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:251:19)
    at parseFieldToPropertyMapping (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:261:26)
    at extractDirectiveMetadata (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:102:30)
    at DirectiveDecoratorHandler.analyze (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:43:35)
    at DecorationAnalyzer.analyzeClass (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.js:105:30)
    at /ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.js:87:87
    at Array.map (<anonymous>)
    at DecorationAnalyzer.analyzeFile (/ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.js:87:51)
    at /ngx-starter-kit/node_modules/@angular/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.js:76:59
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-starter-kit@0.0.0 postinstall: `ivy-ngcc`
npm ERR! Exit status 1
```

#### What is the use-case or motivation for changing an existing behavior?
trying to test `Ivy` 's capability  to produce smaller bundles  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
Angular CLI: 7.3.0-beta.0
Node: 11.6.0
OS: darwin x64
Angular: 8.0.0-beta.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.0-beta.0
@angular-devkit/build-angular      0.13.0-beta.0
@angular-devkit/build-ng-packagr   0.13.0-beta.0
@angular-devkit/build-optimizer    0.13.0-beta.0
@angular-devkit/build-webpack      0.13.0-beta.0
@angular-devkit/core               7.2.2
@angular-devkit/schematics         7.2.2
@angular/cdk                       7.2.1
@angular/cli                       7.3.0-beta.0
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.2.1
@angular/pwa                       0.12.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.0-beta.0
@schematics/angular                7.2.2
@schematics/update                 0.13.0-beta.0
ng-packagr                         4.6.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.28.4
```

#### Is there anything else we should know?
</details>

**Comment by CaerusKaru** [comment]
I don't think it's unreasonable to say that I think the onus here is on the Ivy compiler, since it is meant to be backwards-compatible. That is: there's nothing we can do to fix this issue, it has to be fixed on the angular/angular (which they are actively working to do).

That being said, I'm going to be keeping this issue open so that when Ivy is stable, we can use this to track rewriting the library with Ivy.

**Comment by benneq** [comment]
Any update now that Angular 8 arrived?

When trying to build my project with `"angularCompilerOptions": {"enableIvy": true}` in `tsconfig.app.json` I get errors.

However the compiling process looks fine:
```
...

Compiling @angular/flex-layout/core : es2015 as esm2015

Compiling @angular/flex-layout/extended : es2015 as esm2015

Compiling @angular/flex-layout/flex : es2015 as esm2015

Compiling @angular/flex-layout/grid : es2015 as esm2015

Compiling @angular/flex-layout : es2015 as esm2015

...
```

Here are the errors:
```
ERROR in __ng_typecheck__.ts(112,62): error TS2344: Type '"fxLayout" | "fxLayout.xs" | "fxLayout.sm" | "fxLayout.md" | "fxLayout.lg" | "fxLayout.xl" | "fxLayout.lt-sm" | "fxLayout.lt-md" | "fxLayout.lt-lg" | "fxLayout.lt-xl" | "fxLayout.gt-xs" | "fxLayout.gt-sm" | "fxLayout.gt-md" | "fxLayout.gt-lg"' does not satisfy the constraint '"ngOnChanges" | "activatedValue" | "ngOnDestroy"'.
  Type '"fxLayout"' is not assignable to type '"ngOnChanges" | "activatedValue" | "ngOnDestroy"'.
__ng_typecheck__.ts(113,65): error TS2344: Type '"fxLayoutGap" | "fxLayoutGap.xs" | "fxLayoutGap.sm" | "fxLayoutGap.md" | "fxLayoutGap.lg" | "fxLayoutGap.xl" | "fxLayoutGap.lt-sm" | "fxLayoutGap.lt-md" | "fxLayoutGap.lt-lg" | ... 4 more ... | "fxLayoutGap.gt-lg"' does not satisfy the constraint '"ngOnChanges" | "activatedValue" | "ngOnDestroy" | "ngAfterContentInit"'.
  Type '"fxLayoutGap"' is not assignable to type '"ngOnChanges" | "activatedValue" | "ngOnDestroy" | "ngAfterContentInit"'.
__ng_typecheck__.ts(115,61): error TS2344: Type '"fxFlex" | "fxFlex.xs" | "fxFlex.sm" | "fxFlex.md" | "fxFlex.lg" | "fxFlex.xl" | "fxFlex.lt-sm" | "fxFlex.lt-md" | "fxFlex.lt-lg" | "fxFlex.lt-xl" | "fxFlex.gt-xs" | "fxFlex.gt-sm" | "fxFlex.gt-md" | "fxFlex.gt-lg"' does not satisfy the constraint '"ngOnChanges" | "activatedValue" | "ngOnDestroy" | "shrink" | "grow"'.
  Type '"fxFlex"' is not assignable to type '"ngOnChanges" | "activatedValue" | "ngOnDestroy" | "shrink" | "grow"'.
__ng_typecheck__.ts(116,66): error TS2344: Type '"fxFlexAlign" | "fxFlexAlign.xs" | "fxFlexAlign.sm" | "fxFlexAlign.md" | "fxFlexAlign.lg" | "fxFlexAlign.xl" | "fxFlexAlign.lt-sm" | "fxFlexAlign.lt-md" | "fxFlexAlign.lt-lg" | ... 4 more ... | "fxFlexAlign.gt-lg"' does not satisfy the constraint '"ngOnChanges" | "activatedValue" | "ngOnDestroy"'.
  Type '"fxFlexAlign"' is not assignable to type '"ngOnChanges" | "activatedValue" | "ngOnDestroy"'.
```

But I'm not sure if this library is the issue or my code, because I don't understand what the error messages want to tell me 😄 

So far I can tell, that all fxFlex errors disappear when I remove all fx directives from my code. The error messages above are coming from this little piece of template code:
```html
<mat-card-content fxLayout="column" fxLayoutGap="8px">
  <div fxLayout="row" fxLayoutGap="8px">
      <mat-icon fxFlex fxFlexAlign="center">person</mat-icon>
      <mat-form-field fxFlex="grow">
        <input matInput placeholder="Email" [formControl]="email">
      </mat-form-field>
  </div>
  <div fxLayout="row" fxLayoutGap="8px">
    <mat-icon fxFlex fxFlexAlign="center">lock</mat-icon>
    <mat-form-field fxFlex="grow">
      <input type="password" matInput placeholder="Password" [formControl]="password">
    </mat-form-field>
  </div>
</mat-card-content>
```

**Comment by wynfred** [comment]
@benneq See https://github.com/angular/angular/issues/30114. I'm also waiting for flex-layout to be fixed.

**Comment by RUPALAVECINO** [comment]
¿Tiene alguna solución en este momento?

**Comment by luqezman** [comment]
:(

**Comment by Favna** [comment]
Just as an update of sorts, [angular/angular#30114](https://github.com/angular/angular/issues/30114) as referenced by @wynfred was closed with the supposed resolution being to upgrade to 8.2.0-next.0 for @angular/core but it should be noted that this does not resolve the issue, at least for me. I'm still getting the exact same error. Here is the project I've been trying to get Ivy to work on: https://github.com/favware/website/tree/ivy

**Comment by biltongza** [comment]
Do we consider Ivy stable-ish now that Angular 9 is in RC? Looking for a roadmap of Angular 9 support as this package is one of the blockers upgrading to Angular 9 in my project (not an immediate issue just trying it out to see what we will need to do it).

**Comment by CaerusKaru** [comment]
@biltongza Flex Layout is fully Ivy-compatible as of v8.0.0-beta.27. `ngcc` will convert the library into a suitable Ivy format when you compile your application. This issue is mostly about taking advantage of new Ivy features to attempt to reduce the size and complexity of the library.

**Comment by intellix** [comment]
We're getting this when following the update instructions:
```html
ERROR in ../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:10:7 - error TS1117: An object literal cannot have multiple properties with the same name in strict mode.

10       [fxLayout.xs]="fxLayoutXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:12:7 - error TS1117: An object literal cannot have multiple properties with the same name in strict mode.

12       [fxLayoutGap.xs]="fxLayoutGapXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:10:7 - error TS2349: This expression is not callable.
  Type '{ fxLayout: any; (Missing): any; }' has no call signatures.

10       [fxLayout.xs]="fxLayoutXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:10:7 - error TS18004: No value exists in scope for the shorthand property 'fxLayout'. Either declare one or provide an initializer.

10       [fxLayout.xs]="fxLayoutXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:12:7 - error TS2349: This expression is not callable.
  Type '{ fxLayoutGap: any; (Missing): any; }' has no call signatures.

12       [fxLayoutGap.xs]="fxLayoutGapXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libs/ui/src/lib/formly/flex-layout-type/formly-flex-layout-type.ts:12:7 - error TS18004: No value exists in scope for the shorthand property 'fxLayoutGap'. Either declare one or provide an initializer.

12       [fxLayoutGap.xs]="fxLayoutGapXs"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Splaktar** [comment]
@intellix please open a new issue in angular/angular as that failure is not related to this issue. Also please reference https://github.com/angular/angular/issues/32496 and https://github.com/angular/angular/issues/32099 in your new issue.

**Comment by biltongza** [comment]
I get the same issue as @intellix that's why I asked :)

**Comment by intellix** [comment]
Created @biltongza @Splaktar https://github.com/angular/angular/issues/33590

**Comment by bogacg** [comment]
I had yesterday same error @intellix reported. I remember similar errors were present during Angular v7 to v8 passage. Probably at that time its cause was a different one yet it would be great if this project had a test procedure to catch them on build time and report.

**Comment by CaerusKaru** [comment]
I'm going to close this issue now that we ship the library in partial compilation mode for Ivy. I think "rewriting directives" in retrospect was too broad an ambition. There are certain features we'd like to enable in the framework that are being tracked in other issues. Likewise, a rewrite of the library is being tracked in its respective RFC. If anyone feels strongly about this, please comment with a concrete proposal about how you'd like to proceed and we can reopen.
