### ISSUE TITLE
ERROR: Cannot assign to read only property 'mqAlias' of object '[object Object]'

### ISSUE THREAD

**Issue by muradm** [angular/flex-layout#1013]
#### What is the expected behavior?

No error.

#### What is the current behavior?

```
ERROR TypeError: Cannot assign to read only property 'mqAlias' of object '[object Object]'
    at extendObject (<project-dir>/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:817:31)
    at mergeAlias (<project-dir>/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:2006:12)
    at MediaMarshaller.onMediaChange (<project-dir>/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:3090:18)
```

#### What are the steps to reproduce?

Happens for both browser and SSR project as per [documentation](https://angular.io/guide/universal).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest as of today. 

#### Is there anything else we should know?

Happens [here](https://github.com/angular/flex-layout/blob/c45f2ae0b44ab8f29a4ff9bb858c5cf3d0aae71f/src/lib/core/media-marshaller/media-marshaller.ts#L72) after this [commit](https://github.com/angular/flex-layout/commit/0c9e9cbdb176720042603aed4ebc9f988ff6852d#diff-772f668f85daedbab89a7a3b10556e6b).

**Comment by muradm** [comment]
@CaerusKaru, I think SSR label is not required, happens for browser also.

**Comment by CaerusKaru** [comment]
He @muradm, we need a minimal reproduction to investigate. This doesn't happen with our demo app.

**Comment by muradm** [comment]
@CaerusKaru, on first attempt failed to reproduce it on stackblitz. digging through the flex-layout code also didn't help. i will try to setup simplified project in git repo to localize it later. Any idea or hint on the other possible ways of troubleshooting this?

**Comment by CaerusKaru** [comment]
Not sure, but it really seems like it's not a Flex Layout issue, at least not with the most recent release. I'm closing this due to inactivity, we can reopen if a demo is provided.
