### ISSUE TITLE
Inject() error at angular 14

### ISSUE THREAD

**Issue by matheusim6** [angular/flex-layout#1406]
# Bug Report

#### What is the expected behavior?
FxLayout working as usual.

#### What is the current behavior?
Error when using FxLayoutModule.
```
core.mjs:6751 ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context (a constructor, a factory function or a field initializer). Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context (a constructor, a factory function or a field initializer). Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4863:15)
    at Module.ɵɵinject (core.mjs:4873:12)
    at Object.FlexLayoutModule_Factory [as useFactory] (angular-flex-layout.mjs:63:1)
    at Object.factory (core.mjs:9480:38)
    at R3Injector.hydrate (core.mjs:9393:35)
    at R3Injector.get (core.mjs:9287:33)
    at injectInjectorOnly (core.mjs:4869:33)
    at ɵɵinject (core.mjs:4873:12)
    at useValue (core.mjs:9053:65)
    at R3Injector.resolveInjectorInitializers (core.mjs:9330:17)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26490:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
```

#### What are the steps to reproduce?
Just create a new project with angular 14, and import fxLayout (At this moment it didn't install the dependencies automatically, i had to run npm install rxjs, @angular/core, @angular/common, @angular/platform-browser and @angular/cdk manually). All of them were installed at version 14.0.0, but rxjs, that got 7.5.5.

Here is my package.json:

```
  "dependencies": {
    "@angular/cdk": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/flex-layout": "^13.0.0-beta.38",
    "@angular/platform-browser": "^14.0.0",
    "rxjs": "^7.5.5"
  },

```

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 14

**Comment by matheusim6** [comment]
Solved reinstalling npm.
