### ISSUE TITLE
Plunkr example doesn't work in IE11

### ISSUE THREAD

**Issue by julianobrasil** [angular/flex-layout#225]
I have a layout that breaks in IE11. When I decided to invetigate it I started with the [(plunker template)](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview). The example stucked at the "loading...".

![image](https://cloud.githubusercontent.com/assets/25405143/24040771/571e9a04-0ae9-11e7-892e-84809debfce7.png)

**Comment by ThomasBurleson** [comment]
What is the link to your Plunkr?

**Comment by julianobrasil** [comment]
https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview

**Comment by ThomasBurleson** [comment]
This works for me in:

*  Mac OSX Firefox 52.0 (64-bit)
*  Mac OSX  Chrome 56.0.2924.87 (64-bit)

What are the errors your IE11 is reporting in the dev console ?

**Comment by julianobrasil** [comment]
```
>>>>>>  Error: STACKTRACE TRACKING
>>>>>>    at __SEP_TAG__ (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:43:9)    at getStacktraceWithCaughtError (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:43:9)
>>>>>>    at __SEP_TAG__ (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:43:9)    at LongStackTrace (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:33:9)
>>>>>>    at __SEP_TAG__ (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:43:9)    at captureStackTraces (https://unpkg.com/zone.js/dist/long-stack-trace-zone.js:128:9)
Error: (SystemJS) TypeError: Não é possível obter a propriedade 'apply' de referência indefinida ou nula
	   at combine (eval code:2869:9)
	   at Anonymous function (eval code:2717:5)
	   at ZoneDelegate.prototype.invoke (https://unpkg.com/zone.js@0.7.2?main=browser:227:13)
	   at Zone.prototype.run (https://unpkg.com/zone.js@0.7.2?main=browser:113:17)
	Error loading https://run.plnkr.co/1t88o6Xn6OIyGYuD/src/boot.ts
   {
      [functions]: ,
      __proto__: { },
      description: "(SystemJS) TypeError: Não é possível obter a propriedade 'apply' de referência indefinida ou nula
	   at combine (eval code:2869:9)
	   at Anonymous function (eval code:2717:5)
	   at ZoneDelegate.prototype.invoke (https://unpkg.com/zone.js@0.7.2?main=browser:227:13)
	   at Zone.prototype.run (https://unpkg.com/zone.js@0.7.2?main=browser:113:17)
	Error loading https://run.plnkr.co/1t88o6Xn6OIyGYuD/src/boot.ts",
      message: "(SystemJS) TypeError: Não é possível obter a propriedade 'apply' de referência indefinida ou nula
	   at combine (eval code:2869:9)
	   at Anonymous function (eval code:2717:5)
	   at ZoneDelegate.prototype.invoke (https://unpkg.com/zone.js@0.7.2?main=browser:227:13)
	   at Zone.prototype.run (https://unpkg.com/zone.js@0.7.2?main=browser:113:17)
	Error loading https://run.plnkr.co/1t88o6Xn6OIyGYuD/src/boot.ts",
      name: "Error",
      originalErr: { },
      originalStack: undefined,
      stack: null
   }

```

**Comment by ThomasBurleson** [comment]
@julianobrasil - This ^ is very helpful. Thank you.

**Comment by ThomasBurleson** [comment]
@julianobrasil - The polyfills were wrong in the Template. Please use this:

##### index.html

```html
<!DOCTYPE html>
<html>

  <head>
    <base href="." />
    <title>Flex-Layout Template</title>
    <link rel="stylesheet" href="assets/style.css" />
    
    <!-- Polyfills -->
    <script src="https://unpkg.com/core-js/client/shim.min.js"></script>
    <script src="https://unpkg.com/zone.js@0.7.4?main=browser"></script>
    <script src="https://unpkg.com/systemjs@0.19.39/dist/system.src.js"></script>
    
    <script src="lib/config.js"></script>
    <script>
    System.import('app')
      .catch(console.error.bind(console));
  </script>
  </head>

  <body>
    <test-app>
    loading...
  </test-app>
  </body>

</html>
```

**Comment by julianobrasil** [comment]
Thanks, @ThomasBurleson
