### ISSUE TITLE
Why is it looking for flex-layout.js instead of flex-layout/index.js ?

### ISSUE THREAD

**Issue by Cinemacloud** [angular/flex-layout#252]
I've tried build:components and build:release and copied to node_modules.. but every time I try to import as directions outline I get a complaint of missing flecx-layout.js in browser but appears to compile without complaint ..  it should be looking for flex-layout/index.js or something no? I'm not using umd or anything just trying to do am manual npm compile/install.

**Comment by Cinemacloud** [comment]
Update, I edited seed.config.ts and added two lines for material and now I get this error in browser after it appears to compile without a hitch.. (index):68 (SystemJS) _angular_core.ɵmerge is not a function
	TypeError: _angular_core.ɵmerge is not a function
	    at DirectiveResolver._merge (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13155:74)
	    at DirectiveResolver._mergeWithPropertyMetadata (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13118:21)
	    at DirectiveResolver.resolve (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13054:29)
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13766:64)
	    at CompileMetadataResolver._getEntryComponentMetadata (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:14468:45)
	    at eval (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:14043:53)
	    at Array.map (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:14043:18)
	    at CompileMetadataResolver.getNgModuleSummary (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13893:52)
	    at eval (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13966:72)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13951:49)
	    at CompileMetadataResolver.getNgModuleSummary (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13893:52)
	    at eval (http://new.thejoyhouse.com/angular-seed/dist/dev/node_modules/@angular/compiler/bundles/compiler.umd.js:13966:72)
	    at Array.forEach (native)
	Evaluating http://new.thejoyhouse.com/angular-seed/dist/dev/app/main.js
	Error loading http://new.thejoyhouse.com/angular-seed/dist/dev/app/main.js Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
