### ISSUE TITLE
failed to build (gulp build:components)

### ISSUE THREAD

**Issue by goldenbearkin** [angular/flex-layout#33]
What I done:
1) git clone https://github.com/angular/flex-layout.git
2) cd flex-layout
3) npm install -g yarn
4) yarn install
5) gulp build:components

resulting below:

[19:20:23] Starting ':build:components:ts'...
[19:20:24] TypeScript: emit failed
[19:20:24] Finished ':build:components:ts' after 1.14 s
[19:20:24] Starting ':build:components:rollup'...
[19:20:24] ':build:components:rollup' errored after 2.67 ms
[19:20:24] Error: Could not resolve entry (/development/github/flex-layout/dist/@angular/flex-layout/index.js)
  at /development/github/flex-layout/node_modules/rollup/dist/rollup.js:7309:28
  at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ThomasBurleson** [comment]
Fixed with SHA bc1d45a7644e8d30881673c2ecaa5cc0937c9bb0

> set **noEmit:false** in the `tsconfig.json`.
