### ISSUE TITLE
problem with gulp build:components

### ISSUE THREAD

**Issue by eudago** [angular/flex-layout#37]
gulp  --require ts-node/register build:components

```
[19:11:41] Requiring external module ts-node/register
/Users/eudago/dev/techangelapp/node_modules/@angular/flex-layout/tools/gulp/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import './tasks/ci';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at require.extensions.(anonymous function) (/Users/eudago/dev/techangelapp/node_modules/@angular/flex-layout/node_modules/ts-node/src/index.ts:400:14)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/eudago/dev/techangelapp/node_modules/@angular/flex-layout/node_modules/ts-node/src/index.ts:400:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```
My node version is 7.2.1 and npm 3.10.10
Gulp version 3.9.0 but i test with 3.9.1 and not working

**Comment by ThomasBurleson** [comment]
try `gulp build:components` after `yarn install`

**Comment by eudago** [comment]
I follows these steps (README)

```
npm install -g yarn
yarn install
gulp build:components

```

and not work.

**Comment by TimoKunze** [comment]
Same problem here. I did follow the steps from the README, but get the same error as eudago.

**Comment by ThomasBurleson** [comment]
@eudago, @TimoKunze - thank you. We will investigate

**Comment by chpasha** [comment]
I'm getting some of the files with size 0 after gulp build:components
@angular/flex-layout/media-query/breakpoints/break-point-registry.d.ts
@angular/flex-layout/utils/auto-prefixer.d.ts
@angular/flex-layout/utils/object-extend.d.ts

**Comment by christophechevalier** [comment]
![image](https://cloud.githubusercontent.com/assets/7148846/21144632/b9ef9d00-c14b-11e6-9b37-bcf1f8d23017.png)

I also have an error in case it might help !

**Comment by ThomasBurleson** [comment]
`gulp build:components` should now be fixed with the latest commits.

**Comment by ThomasBurleson** [comment]
Please use `gulp build:lib` or `gulp build:release`.
