### ISSUE TITLE
gulp build:release error

### ISSUE THREAD

**Issue by paulogr** [angular/flex-layout#41]
I'm trying to build the project to use it but getting the below error

My environment is

- node: 6.5.0
- typescript: 2.1.4

Thank you for help.

```MacBook-Pro-de-moby:flex-layout paulogr$ gulp build:release
[00:54:04] Using gulpfile ~/dev/flex-layout/gulpfile.js
[00:54:04] Starting 'build:release'...
[00:54:04] Starting 'clean'...
[00:54:04] Finished 'clean' after 52 ms
[00:54:04] Starting ':build:components:ts'...
[00:54:06] Finished ':build:components:ts' after 2.66 s
[00:54:06] Starting ':build:components:rollup'...
[00:54:08] Finished ':build:components:rollup' after 1.28 s
[00:54:08] Starting 'build:components'...
[00:54:08] Finished 'build:components' after 6.85 μs
[00:54:08] Starting ':build:components:ngc'...
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (/Users/paulogr/dev/flex-layout/node_modules/typescript/lib/typescript.js:78080:30)
    at Evaluator.evaluateNode (/Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/evaluator.js:495:66)
    at _loop_1 (/Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/collector.js:306:54)
    at /Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/collector.js:365:25
    at visitEachNode (/Users/paulogr/dev/flex-layout/node_modules/typescript/lib/typescript.js:13907:30)
    at Object.forEachChild (/Users/paulogr/dev/flex-layout/node_modules/typescript/lib/typescript.js:14078:24)
    at MetadataCollector.getMetadata (/Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/collector.js:204:12)
    at MetadataWriterHost.writeMetadata (/Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (/Users/paulogr/dev/flex-layout/node_modules/@angular/tsc-wrapped/src/compiler_host.js:103:19)
    at Object.writeFile (/Users/paulogr/dev/flex-layout/node_modules/typescript/lib/typescript.js:62522:132)
Compilation failed
[00:54:13] ':build:components:ngc' errored after 5.16 s
[00:54:13] Error: Process failed with code 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/index.js:264:8)
    at /Users/paulogr/dev/flex-layout/node_modules/orchestrator/index.js:275:23
    at finish (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/paulogr/dev/flex-layout/tools/gulp/task_helpers.ts:93:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
[00:54:13] 'build:release' errored after 9.18 s
[00:54:13] Error in plugin 'run-sequence(:build:components:ngc)'
Message:
    Process failed with code 1
Stack:
    at finish (/Users/paulogr/dev/flex-layout/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/paulogr/dev/flex-layout/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/index.js:264:8)
    at /Users/paulogr/dev/flex-layout/node_modules/orchestrator/index.js:275:23
    at finish (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/paulogr/dev/flex-layout/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/paulogr/dev/flex-layout/tools/gulp/task_helpers.ts:93:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)```

**Comment by kuncevic** [comment]
Getting same error here when running `gulp build:release`

**Comment by ThomasBurleson** [comment]
@paulogr - are you on Windows? Which version is your `node_modules/.bin/tsc --version` ?

**Comment by ThomasBurleson** [comment]
The webpack builds (for the demos) work and `gulp build:components` now works. I also fixed and issues with a missing export in the lib. (see HEAD)

Currently this release issue is something associated the **compiler-cli**.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 2a1590a30063a58734951f67f3f6c4bbe71090d7 + SHA 3f2aa2167efc741f8eab27d8198b17f54a22c21d.

**Comment by kuncevic** [comment]
@ThomasBurleson I just did pull the latest and reinstall npm packages and uncommented the ` FlexLayoutModule.forRoot()`  so it is seams to be now.
 
I see you downgraded pretty mutch all angular related packages from `2.3` to `2.2.4` exept `zone.js` which you updated to most recent one as per that commit: https://github.com/angular/flex-layout/commit/3f2aa2167efc741f8eab27d8198b17f54a22c21d. 
Is there still issues with the latest angular compiler?

**Comment by paulogr** [comment]
It's now works here!
