### ISSUE TITLE
Function load error: Code in file index.js can't be loaded. 

### ISSUE THREAD

**Issue by coderrepo** [angular/flex-layout#720]
All of the sudden functions publish error. 

Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: core.defineInjectable is not a function
    at /user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:459:66
    at /user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:461:2
    at Object.setPrototypeOf.__proto__ (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:9:65)
    at Object.<anonymous> (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:12:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by CaerusKaru** [comment]
It is nearly impossible to decipher what the issue is from the information given. Please follow the issue template and open a new issue with the necessary information to debug.
