### ISSUE TITLE
Detailed stack trace: TypeError: core.defineInjectable is not a function

### ISSUE THREAD

**Issue by coderrepo** [angular/flex-layout#722]
#### Bug, feature request, or proposal:
This is the angular universal apps render using Firebase function 

#### What is the expected behavior?
Should work in the production environment

#### What is the current behavior?
Website not working due to this issue

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.10",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "express": "^4.16.3",
    "firebase-admin": "~5.12.0",
    "firebase-functions": "^1.0.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@ngx-progressbar/core": "^4.3.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/quill": "1.3.6",
    "angular2-text-mask": "^8.0.4",
    "codelyzer": "^4.0.1",
    "core-js": "^2.4.1",
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0",
    "i": "^0.3.6",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-image-cropper": "^0.2.2",
    "protractor": "~5.1.2",
    "quill": "1.3.5",
    "rxjs": "^5.5.6",
    "ts-node": "~4.1.0",
    "tslib": "^1.9.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  },

#### Is there anything else we should know?
Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: core.defineInjectable is not a function
    at /user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:459:66
    at /user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:461:2
    at Object.setPrototypeOf.__proto__ (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:9:65)
    at Object.<anonymous> (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout-core.umd.js:12:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by CaerusKaru** [comment]
Any chance this is a duplicate of #714?

You can tell by running `npm ls @angular/flex-layout` and checking the version number

**Comment by coderrepo** [comment]
`-- @angular/flex-layout@5.0.0-beta.14

**Comment by CaerusKaru** [comment]
Can you post a link to a GitHub repo that replicates this (or a StackBlitz reproduction)?

**Comment by CaerusKaru** [comment]
The reason I suspect you're not using the right version is because the source for that bundle, found [here](https://unpkg.com/@angular/flex-layout@5.0.0-beta.14/bundles/flex-layout-core.umd.js) contains no reference to `defineInjectable` whereas the version from the issue I linked to [does](https://unpkg.com/@angular/flex-layout@5.0.0-beta.14-17a70ee/bundles/flex-layout-core.umd.js)
